name: Build and Deploy Recipe Book

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: whiskly
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
                  cache: 'npm'
                  cache-dependency-path: whiskly/package-lock.json

            - name: Install dependencies
              run: npm install

            - name: Build and deploy the Recipe Book
              run: npm run deploy
              env:
                GH_TOKEN: ${{ secrets.GIUTHUB_TOKEN }}